### PR TITLE
update 404 page

### PR DESCRIPTION
**Pull request by wslack**
I'm sure I typoed some of the HTML

### CODE REVIEW

**Comment by amirbey** [comment]
how about:

There is no page at the requested address. Click <a href="/">here</a> to return to the homepage.

**Comment by amirbey** [comment]
I agree with you on the Corey's suggestion.
If you do not prefere previously suggested : "The is no page at the requested address."
How about adding "found": "There was no page found at the requested address."

**Comment by wslack** [comment]
Edited! What about the "Federalist" part of the text?

**Comment by wslack** [comment]
@amirbey can you please look at codeclimate and verify Jonathan's linting edits?

**Comment by amirbey** [comment]
@jmhooper - can you also approve ... i made a commit to remove a space

**Comment by amirbey** [comment]
registry pushed to registry staging

**Pull request merged**
